### ISSUE TITLE
onMessage problem

### ISSUE THREAD

**Issue by k4r3l01** [gave92/fbchat-sharp#30]
Hello please i have problem with onMessage event.
This event stop working after few hours without any error i think its stop listening. and i dont know how to print debug messages :( to console and better to file

**Comment by gave92** [comment]
Hello, in case you haven't try again with the latest commit in the develop branch. It should automatically reconnect in case of client disconnecting. Please let me know

**Comment by k4r3l01** [comment]
Hello i using this commit and with this commit i have disconnect problem

**Comment by gave92** [comment]
Thanks for the feedback. Let me know if commit 0a2c806efc8cbe5aa8013c8fb8b4d9b56c358517 fixes the issue.

**Comment by k4r3l01** [comment]
thanks i will try

**Comment by k4r3l01** [comment]
Hello so it looks like it works

**Comment by gave92** [comment]
Closing this, feel free to reopen if ylhave further issues

**Comment by k4r3l01** [comment]
Hello so now i have similiar problem but in debug log i have this 
`Vyvolaná výjimka: fbchat_sharp.API.FBchatPleaseRefresh v fbchat-sharp.dll
Vyvolaná výjimka: fbchat_sharp.API.FBchatPleaseRefresh v fbchat-sharp.dll
Vyvolaná výjimka: fbchat_sharp.API.FBchatPleaseRefresh v System.Private.CoreLib.dll
Vyvolaná výjimka: fbchat_sharp.API.FBchatPleaseRefresh v System.Private.CoreLib.dll
Vyvolaná výjimka: fbchat_sharp.API.FBchatPleaseRefresh v System.Private.CoreLib.dll
Vyvolaná výjimka: fbchat_sharp.API.FBchatPleaseRefresh v System.Private.CoreLib.dll
Vyvolaná výjimka: fbchat_sharp.API.FBchatPleaseRefresh v System.Private.CoreLib.dll
Vyvolaná výjimka: fbchat_sharp.API.FBchatPleaseRefresh v System.Private.CoreLib.dll
Vyvolaná výjimka: fbchat_sharp.API.FBchatPleaseRefresh v System.Private.CoreLib.dll
Vyvolaná výjimka: fbchat_sharp.API.FBchatPleaseRefresh v System.Private.CoreLib.dll
fbchat_sharp.API.FBchatPleaseRefresh: Error #1357004 when sending request: Zkuste zavřít a opět otevřít okno prohlížeče.
   at fbchat_sharp.API.State._post(String url, Dictionary`2 query, Dictionary`2 files, Boolean as_graphql, CancellationToken cancellationToken) in x:\fbchat-dev2\fbchat-sharp\API\State.cs:line 488
   at fbchat_sharp.API.State.graphql_requests(List`1 queries) in x:\fbchat-dev2\fbchat-sharp\API\State.cs:line 520
   at fbchat_sharp.API.Client.graphql_requests(List`1 queries) in x:\fbchat-dev2\fbchat-sharp\API\Client.cs:line 126
   at fbchat_sharp.API.Client.fetchThreadInfo(List`1 thread_ids) in x:\fbchat-dev2\fbchat-sharp\API\Client.cs:line 828
   at fbchat_sharp.API.Client.fetchUserInfo(List`1 user_ids) in x:\fbchat-dev2\fbchat-sharp\API\Client.cs:line 716
   at examples.FBClient_Cookies.onMessage(String mid, String author_id, String message, FB_Message message_object, String thread_id, Nullable`1 thread_type, Int64 ts, JToken metadata, JToken msg) in x:\fbchat-dev2\examples\netcore\FBClient_Cookies.cs:line 34
   at fbchat_sharp.API.Client._parseDelta(JToken m) in x:\fbchat-dev2\fbchat-sharp\API\Client.cs:line 3357
   at fbchat_sharp.API.Client._parse_mqtt(String event_type, JToken event_data) in x:\fbchat-dev2\fbchat-sharp\API\Client.cs:line 3755
   at fbchat_sharp.API.Client._try_parse_mqtt(String event_type, JToken event_data) in x:\fbchat-dev2\fbchat-sharp\API\Client.cs:line 3715`

**Comment by gave92** [comment]
hello commit 7b375c74dead65583399cb2ae0e6027ec80e4249 should help with that.
please not that some methods (e.g. `TryLogin()` and `DoLogin()`) have changes slightly. You can check the examples for the encessary modifications.

**Comment by k4r3l01** [comment]
thanks its seems to working now correctly for now running 28 hours without problems
