### ISSUE TITLE
FetchThreadList() returns null

### ISSUE THREAD

**Issue by jmbits** [gave92/fbchat-sharp#8]
I was following the examples, but I receive the following exception:

System.ArgumentNullException
  HResult=0x80004003
  Message=Value cannot be null.
  Source=System.Private.CoreLib
  StackTrace:
   at System.String.Replace(String oldValue, String newValue)
   at fbchat_sharp.API.GraphQL_JSON_Decoder.graphql_to_thread(JToken thread)
   at fbchat_sharp.API.Client.<>c.<fetchThreadList>b__62_0(JToken node)
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at fbchat_sharp.API.Client.<fetchThreadList>d__62.MoveNext()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()

Any idea why this is happening?

**Comment by gave92** [comment]
Hello thanks for reporting this, I'll look into it when I can.
In the meantime you can edit the library code yourself if you want.
The offending line should be https://github.com/gave92/fbchat-sharp/blob/8db21aab2365648acba96f6f686f68cb97fda0a9/fbchat-sharp/API/GraphQl.cs#L281

**Comment by gave92** [comment]
Fixed in a4e19e37e9281cd38d2a994ea7e5cab1fb8cdc8a

**Comment by jmbits** [comment]
It is working. Thanks a lot!
